### ISSUE TITLE
This dist needs a new maintainer =/

### ISSUE THREAD

**Issue by TiMBuS** [tobyink/p5-kavorka#20]
This module (along with Moops) was once considered to be a gigantic leap forward for Perl (esp. with the successful use of token parsing instead of source filters). It has helped me write some incredibly safe, maintainable code for my work and home projects.

It's rather obvious that Toby is no longer active. It's a huge shame, but it would be nice if someone could at least keep the lights on.
I don't feel qualified, especially with how much magic is in here.. But is anyone willing + available to fix up the outstanding issues and publish a new version to cpan?

**Comment by baby-gnu** [comment]
Hello,

I think Kavorka could be rewritten/replaced using perl [syntax](https://metacpan.org/pod/syntax) like [Function::Parameters](https://metacpan.org/pod/Function::Parameters).

I'm not very confident neither with Kavorka code nor with perl syntax.

It looks to me that [Function::Parameters](https://metacpan.org/pod/Function::Parameters):

- has some divergences with Kavorka on the declaration of [optional positional parameters](https://metacpan.org/pod/Function::Parameters#Optional-positional-parameters) and [optional named parameters](https://metacpan.org/pod/Function::Parameters#Optional-named-parameters)
- does not handle everything that Kavorka does like multi

Searching metacpan, I just found [Dios](https://metacpan.org/pod/Dios) from Damian Conway which looks cool for Perl6 like syntax, but I'm not sure how it interact with [Moops](https://metacpan.org/pod/Moops) (either with [Moo](https://metacpan.org/pod/Moo) or [Moose](https://metacpan.org/pod/Moose)) since it's based on [Object::InsideOut](https://metacpan.org/pod/Object::InsideOut).

I have some amount of code using [Moops](https://metacpan.org/pod/Moops), switching for something maintained is not an easy option :-/.

Regards.

**Comment by TiMBuS** [comment]
`syntax` is just a pragma, I don't think it helps here. And switching this module to use Dios is probably.. wrong. However it would make perfect sense for this module to use the `Keyword::Declare` / `Keyword::Simple` that Dios uses, instead of using a patched `Parse::Keyword`.

That being said it isn't necessary to change the underlying code. The patches Toby made for Parse::Keyword seem perfectly safe.. In fact this whole module seems pretty good in general, it just needs someone to keep it up to date with newer perls, and maybe make improvements where possible.

**Comment by baby-gnu** [comment]
My fault, I was not clear:

* I'm not thinking of using [Dios](https://metacpan.org/pod/Dios) for this module but replace `Parse::Keyword` with more standard features like the perl [plugin keyword API](https://metacpan.org/pod/perlapi#PL_keyword_plugin) used by `Function::Parameters`, but [Keyword::Simple](https://metacpan.org/pod/Keyword::Simple) use it too
* I wondered if it could be worth to swith to [Dios](https://metacpan.org/pod/Dios) for my own future code

The better long term option may be to switch to [Keyword::Simple](https://metacpan.org/pod/Keyword::Simple).

Regards.

**Comment by TiMBuS** [comment]
I'm going to be a bit bold and tag @karenetheridge and @paultcochrane here, as they both have forks of this project and I know Karen in particular isn't a stranger to fostering modules.. Might have some wisdom to share on the subject, because I'd really like this distro to stay alive.

**Comment by karenetheridge** [comment]
I believe @tobyink was making a bit of a comeback in order to tend to maintenance issues -- now's a good time to tag him in anything that he needs to look at soon.  I'm happy to help with maintenance, but that may not be needed just yet.

**Comment by TiMBuS** [comment]
Well I don't think anyone (including TobyInk) would take issue with you merging the outstanding pull requests and releasing a v0.037 -- I'd personally be very grateful.

But if you have reason to believe TobyInk will be back soon I guess I can wait.

**Comment by tobyink** [comment]
I think tobyink will probably be back.

It looks like he's recently updated Exporter::Tiny and Type::Tiny, so I guess he'll get around to fixing Kavorka and Moops at some point.
